### ISSUE TITLE
uss_qualifier quick start failed at step make start-uss-mocks

### ISSUE THREAD

**Issue by davidqqq** [interuss/monitoring#14]
**Describe the bug**

`make start-uss-mocks` failed at requirements.txt installation.

```
#9 8.060   × Getting requirements to build wheel did not run successfully.
#9 8.060   │ exit code: 1
#9 8.060   ╰─> [1 lines of output]
#9 8.060       proj executable not found. Please set the PROJ_DIR variable. For more information see: https://pyproj4.github.io/pyproj/stable/installation.html
#9 8.060       [end of output]
```

Updated pyproj from 3.0.0 to 3.3.0 worked.

Next the Shapely==1.7.1 complained about
```
FileNotFoundError: Could not find module 'geos_c.dll' (or one of its dependencies). Try using the full path with constructor syntax.
      [end of output]
```
Adding apt-get install -y libgeos-dev to Dockerfile solved the issue.

In summary, updated pyproj from 3.0.0 to 3.3.0 and added libgeos-dev.

However pyproj=3.0.0 installed just fine on python3.8 in my host. Not sure why pyproj==3.0.0 failed to install in Docker.

**To Reproduce**
1. Check out this repository: `git clone https://github.com/interuss/monitoring`
2. Go to repository root: `cd monitoring`
3. Bring up a local UTM ecosystem (DSS + dummy auth): `make start-locally`
4. Bring up mock USSs: `make start-uss-mocks`

**Expected behavior**

Should bring up mock USSs

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOS
 - Version [e.g. 22] 13.0.1

**Smartphone (please complete the following information):**

**Additional context**

**Comment by BenjaminPelletier** [comment]
That seems very odd as I thought our CI builds images from scratch.  I tried reproducing from head on my MacOS dev machine by first `docker rmi $(docker images -q)`, then `make start-locally`, then `make start-uss-mocks` and couldn't reproduce with that (everything built and run successfully).  It seems like monitoring/build.sh should reproduce the issue with fewer steps if that's helpful.

Are you maybe using a different processor architecture?  I think the newer Macs may have something different than my not-quite-new Mac.  Just trying to think of something that might cause the different results since Docker builds are supposed to be reproducible between machines.

In any case, it seems like updating to 3.3.0 + installing libgeos-dev shouldn't hurt.

**Comment by davidqqq** [comment]
Hi thanks for looking into this. I believe both error are to do with Mac M1. The pyproj only supported newer Mac in its most recent release 3.4.1. Prior to 3.1.0 there is no wheel for arm and not until 3.4.1 does it has wheel for MacOS arm (pyproj-3.4.1-cp38-cp38-macosx_11_0_arm64.whl). My statement that 

> However pyproj=3.0.0 installed just fine on python3.8 in my host. 

must be a wrong observation

Similarly for shapely==1.7.1,  it has M1 [issue](https://github.com/shapely/shapely/issues/1080) too.

Also use pyproj=3.1.0, instead of 3.3.0 because newer version of [PROJ forbids zone as a string](https://github.com/OSGeo/PROJ/pull/2672). Thus `Proj(proj="utm", zone=self.utm_zone, ellps="WGS84", datum="WGS84")` will error as utm_zone here is a string.

Hope anyone come across this issue can save some time searching.

**Comment by BenjaminPelletier** [comment]
Thanks for looking into this.  I think we should be able to update pyproj + shapely; it seems like changing zone from a string shouldn't be too difficult (and is probably a cleaner way to do things any way).  We would welcome a PR if possible, or otherwise we'll still plan to address the issue.
