### ISSUE TITLE
Activation before Operation Start Time

### ISSUE THREAD

**Issue by hsrodriguez** [interuss/monitoring#301]
When an operation is injected using the endpoint `PUT http://host.docker.internal:9090/v1/flights/%7Bid%7D` and the state in the payload is `Activated`, the start time of the volumes should be the current or past date/time. Note: This applies for both the following injections:
Modifying to update the operation to the "Activated" state
Modifying any other operation details while remaining in the "Activated" state
The logic here is that if an operation is in the "Activated" state, then the volumes are notionally being utilized by the operator. This is impossible if the volumes' earliest start time is still in the future.
From a automation testing standpoint, where speed of the automation test is key, we see it to be adequate to do one of the following:
Originally set operation start times to be very near in the future (~5 seconds from when the operation is Accepted), or
Simultaneously update the start time of the operation when transitioning to the Activated state
This way we don't have to incorporate large delays in automation test runs waiting for activation times to approach.

**Comment by BenjaminPelletier** [comment]
This sounds like #217; could you confirm which commit/codebase version you're using?  All our volumes now should [start before activation time](https://github.com/interuss/monitoring/blob/7fb0ef7d634a751539438f2c5524512b42785e02/monitoring/uss_qualifier/test_data/che/flight_intents/conflicting_flights.yaml#L134).

Per [bug template for "Test scenario bug"](https://github.com/interuss/monitoring/issues/new?assignees=&labels=test-scenario-behavior%2C+automated-testing&projects=&template=bug_test_scenariog.md), it would be great to have one of the artifacts produced by the test so we can see exactly what the problem is.

**Comment by hsrodriguez** [comment]
Thanks @BenjaminPelletier , I do have an older version. I will update and run the tests again.
