### ISSUE TITLE
unexpected mock USS error when running "Data Validation of GET operational intents by USS"

### ISSUE THREAD

**Issue by vgrafe** [interuss/monitoring#368]
A mock USS server is buggy in my environment.

Test in question: [Data Validation of GET operational intents by USS](https://github.com/interuss/monitoring/blob/3295d6256c65973191f6bb2d69cc9c4d125637ec/monitoring/uss_qualifier/scenarios/astm/utm/data_exchange_validation/get_op_data_validation.md)
scenarios.astm.utm.data_exchange_validation.GetOpResponseDataValidationByUSS

[report.json.zip](https://github.com/interuss/monitoring/files/13462612/report.json.zip)
[scdsc_interaction_logs.zip](https://github.com/interuss/monitoring/files/13462613/scdsc_interaction_logs.zip)

A call is made to `http://scdsc.log.uss6.localutm/mock/scd/uss/v1/operational_intents/5b147417-2efe-4fda-8aed-f7009d6cbcf7` from the USS, with a 500 response. When looking at `scdsc.log.uss6.localutm/`'s logs, the following can be found: 

```
[2023-11-25 00:07:32,319] ERROR in app: Exception on /mock/scd/uss/v1/operational_intents/5b147417-2efe-4fda-8aed-f7009d6cbcf7 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/werkzeug/wrappers/request.py", line 586, in get_json
    rv = self.json_module.loads(data)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by vgrafe** [comment]
The USS under test does return 500 as a result of the peer call made to the mock uss failing with a http 500, which is detailed in the code snippet written last in the bug report.

Would this fact make you reconsider the issue's severity/priority? I can fish for more extensive logs from the mock USS if needed.

**Comment by BenjaminPelletier** [comment]
The USS under test returning 500 indicates a problem in the USS under test which should be fixed -- the expected outcome for a downstream failure is 200 indicating [Failed](https://github.com/interuss/automated_testing_interfaces/blob/8a5f1db0f59b8fcce1c6095bcec17e994df0fb75/flight_planning/v1/flight_planning.yaml#L201).

Furthermore, the mock_uss logs provided indicate that the JSON body of the request sent to mock_uss (presumably by the USS under test) was invalid, which indicates a second problem in the USS under test.

Upon resolution of this issue, mock_uss would indicate 400 to the USS under test saying the JSON body was invalid (rather than 500), and then presumably the first issue (the USS under test reporting 500 rather than failure) would still be present as would the second issue (the USS under test providing an invalid request body) -- the only thing that would have changed would have been a different error code and error message from mock_uss.  We will fix that issue, but it doesn't seem to be blocking identification or resolution of the two issues identified with the USS under test in this case, hence P2.

**Comment by vgrafe** [comment]
Ah, I got it now. Thanks for the clarification.

**Comment by vgrafe** [comment]
I fixed the tested USS behavior to not throw 500 on downstream error. Unfortunately the test suite still crashes with error logs that hints at an error in the mock USS code. This also seems to crash the HTML report generation as shown below. It looks like the code that composes the error message that should be returned by the mock USS has a bug.

Sorry if I am not seeing something obvious here. I tried adding print statements in the mock source code without success getting more info on what exactly causes the error.

![Screenshot 2023-11-28 at 12 27 39 PM](https://github.com/interuss/monitoring/assets/3950855/a18c06b1-abfc-46a5-9674-98c788d0c0b7)

**Comment by BenjaminPelletier** [comment]
Thanks, yes, that is a second InterUSS bug and unfortunately it's preventing us from definitively identifying what the unexpected planning result was.  The USS under test is still going to fail a check once this second bug is resolved (the bug is in producing the message about the failure), but resolving this second bug will provide more information about why the USS under test fails that check.  Based on the thread so far, I'll guess that the result was Failed due to the JSONDecodeError in mock_uss which indicates that a valid request body was not provided to mock_uss.  If you want a quick hot fix while this bug is addressed (upgrading to P1 since it is now blocking definitive test results), line 442 of test_steps.py (mentioned 5 lines from the bottom of your stacktrace) should actually be `summary=f"Flight unexpectedly {resp.activity_result}",`

Side note: just as mock_uss should never return 500 (and therefore the issue in the first comment on this thread definitely includes a mock_uss bug), uss_qualifier should never have an exception (and therefore the issue in the comment just prior to this one definitely includes a uss_qualifier bug).

**Comment by vgrafe** [comment]
It might be worth mentioning that this error stack is headed with the following: ```[2023-11-28 19:52:47,657] ERROR in app: Exception on /mock/scd/uss/v1/operational_intents/d16fa38e-7d8f-4f6b-a145-24b6d3afa014 [GET]```

The error happens upon querying the mock USS for a specific opint by providing an ID as a path parameter. This also suggests to me that the bug does not come from the tested USS sending malformed data, unless it is received and saves on a previous step.

**Comment by vgrafe** [comment]
Thank you for merging changes related to this - I could fix all issues I had on my end, and now all the tests pass. Thanks again for being reactive on this.

**Comment by BenjaminPelletier** [comment]
No problem; thanks for raising and working with us :)

Closed issues can be reopened in the future if we ever close them in error, FYI
