### ISSUE TITLE
Residual subscriptions during F3548 testing

### ISSUE THREAD

**Issue by punamverma** [interuss/monitoring#415]
**Describe the bug**
There are some tests that are not cleaning up their subscriptions, leading to unreliable run in - Data Validation of GET operational intents by USS - scenario.

**To reproduce**
1. Run uss_qualifier tests on CI
2. Check report.json under output/f3548
3. In the report, go to  "Data Validation of GET operational intents by USS" test scenario> Successfully plan flight near an existing flight > Check for notification to tested_uss due to subscription in flight 2 area test step > queries > response > json > interactions
4. You will see there is POST notification made using 8 subscriptions, which is due to other tests that didn't clean their operations and hence subscriptions.

**Difference from expected behavior**
Should not get notifications due to existing subscriptions, while control_uss planning flights in "Data Validation of GET operational intents by USS" test scenario.

**Possible solution**
Investigate which tests are not cleaning up, and fix the cleanup.

**Screenshots**
Attaching a sample report.json file
[report.json](https://github.com/interuss/monitoring/files/13691229/report.json)

**System on which behavior was encountered**
OS: [e.g. iOS, Windows, Linux; include version and/or other information if it may be relevant]

**Codebase information**
Currently seen in tests run while running tests in PR - https://github.com/interuss/monitoring/pull/376

**Additional context**

**Comment by BenjaminPelletier** [comment]
Note that tests don't have subscriptions, but rather USSs participating in tests have subscriptions (and sometimes USSs not participating in tests have subscriptions).  If mock_uss is not behaving correctly, it would be great to develop a uss_qualifier test scenario + check that will fail so that we can detect this kind of non-compliance in other USSs as well (and then fix mock_uss).  If mock_uss is behaving correctly and the uss_qualifier scenarios are issuing instructions that cause USSs in general to be likely to leave subscriptions behind, then definitely let's update those scenarios to better clean up after themselves.  If a requirement isn't being violated and changing the scenarios is difficult or ineffective, it could be that the expectation of no subscriptions is not a good expectation -- the presence of one or more subscriptions alone doesn't establish that something is wrong.

**Comment by BenjaminPelletier** [comment]
DSS0005(1) requires a DSS implementation to comply with the OpenAPI spec which says that implicit subscriptions created upon either creation or update of an operational intent reference [should be deleted](https://github.com/astm-utm/Protocol/blob/v1.0.0/utm.yaml#L773)<sup>1</sup> upon deletion of the corresponding operational intent reference.  It would be great to create a test scenario to check this behavior, or update existing scenario(s) to check this behavior.

In the InterUSS implementation, my expectation is: When an implicit subscription is created, it fully covers the operational intent reference.  Therefore, if there was a pre-existing implicit subscription, it should be deleted when the new implicit subscription is created if the old implicit subscription wasn't serving any other purpose (no reason to have two subscriptions to serve the same notification purpose).  Also, I would expect that if the InterUSS DSS would create a new implicit subscription that is effectively the same as an old implicit subscription, the old implicit subscription would instead be mutated and no new implicit subscription would be created.

<sup>1</sup>Documentation says this should happen "generally", but I think it's fair to assume it should happen unless there is a specific reason for it not to happen.  The only reason I would expect it not to happen is if that implicit subscription was then used explicitly to create or update another operational intent reference.

**Comment by BenjaminPelletier** [comment]
I think a good scenario to verify correct DSS management of implicit subscriptions would be:

<table>
  <tr><th>Op intent</th><th>State</th><th>Relevant to</th><th>Does not intersect with</th></tr>
  <tr><td>OI1</td><td>Any nominal</td><td>OI2, OI3</td><td>OI2, OI3</td></tr>
  <tr><td>OI2</td><td>Planned</td><td>OI1, OI3</td><td>OI1, OI3</td></tr>
  <tr><td>OI3</td><td>Any nominal</td><td>OI1, OI2</td><td>OI1, OI2</td></tr>
</table>

t<sub>now</sub> << t<sub>1</sub> < t<sub>2</sub> < t<sub>3</sub>

1. Create OI3 in DSS from t<sub>2</sub> to t<sub>3</sub>
2. Note any pre-existing subscriptions based on the subscribers in response to OI3 creation
3. Delete OI3 from DSS (and possibly confirm pre-existing subscriptions based on subscribers)
4. Create OI1 in DSS from t<sub>now</sub> to t<sub>3</sub> using implicit subscription
5. Create OI2 in DSS from t<sub>2</sub> to t<sub>3</sub> without subscription, confirm OI1's implicit subscription is among subscribers
6. Update OI1 in DSS to be from t<sub>now</sub> to t<sub>1</sub>
7. Create OI3 in DSS from t<sub>2</sub> to t<sub>3</sub>, confirm no subscriptions beyond pre-existing subscriptions in step 2 are among subscribers
8. Clean up

**Comment by Shastick** [comment]
@BenjaminPelletier I'm working on the scenario to check this and need to confirm some assumptions:

Taking the 8 steps you described:

>     1. Create OI3 in DSS from t2 to t3

I assume OI3 should not specify a subscription id, and an implicit subscription should be created.
 
>     2. Note any pre-existing subscriptions based on the subscribers in response to OI3 creation
> 
>     3. Delete OI3 from DSS (and possibly confirm pre-existing subscriptions based on subscribers)

After deletion of OI3, I assume that the corresponding implicit subscription should be deleted (ie, querying it should result in a 404), [as described in the OpenAPI spec](https://github.com/astm-utm/Protocol/blob/v1.0.0/utm.yaml#L773)

Note that this [currently fails on the DSS](https://github.com/interuss/monitoring/pull/720): removing an OIR that caused the creation of an implicit subscription, and if the implicit subscription has no other OIR covered, the subscription can still be found. I assume this is an issue of the DSS, from what I can see, the implicit subscription covered _only_ the created OIR (ie, it is not a leftover from a previous scenario)

>     4. Create OI1 in DSS from tnow to t3 using implicit subscription

Does _using implicit subscription_  here mean: 
 - "reuse implicit subscription from OI3" (which in my current understanding of things should fail, because the subscription was cleaned up)
 - "create without specifying a subscription id, specify that an implicit subscription should be created if required, expect an implicit one to be created or attached"

>     5. Create OI2 in DSS from t2 to t3 without subscription, confirm OI1's implicit subscription is among subscribers

In addition to having OI1's subscription mentioned in subscribers, I _also_ assume that the subscription that gets attached is the one of OI1 (assuming that the initial implicit subscription for OI3 has been removed)

>     6. Update OI1 in DSS to be from tnow to t1

Here, from my understanding, what should generally happen is that a new implicit subscription should be created and attached to OI1, as OI1 and OI2 are now entirely disjoint.

I am wondering if it would be acceptable for a DSS to not do anything with the implicit subscription, as it technically still covers both OI1 and OI2, although it also covers the interval from t_1 to t_2 where nothing exists? My hunch would be to not accept this, but I'd like a second opinion on that matter.

>     7. Create OI3 in DSS from t2 to t3, confirm no subscriptions beyond pre-existing subscriptions in step 2 are among subscribers

Here OI3 should be attached to the implicit subscription created in step 4 that now only covers OI2, assuming that step 6 caused the creation of a new implicit subscription.

>     8. Clean up

**Comment by BenjaminPelletier** [comment]
> I assume OI3 should not specify a subscription id, and an implicit subscription should be created.

It shouldn't matter (the scenario should work the same regardless of whether OI3 uses an explicit or implicit subscription), but yes, I would expect an implicit subscription should be easiest.

> After deletion of OI3, I assume that the corresponding implicit subscription should be deleted (ie, querying it should result in a 404), as described in the OpenAPI spec

Yes (assuming OI3 used an implicit subscription)

> Does using implicit subscription here mean:
>
> * "reuse implicit subscription from OI3" (which in my current understanding of things should fail, because the subscription was cleaned up)
> * "create without specifying a subscription id, specify that an implicit subscription should be created if required, expect an implicit one to be created or attached"

Providing a pre-existing subscription for an operational intent would be specifying an explicit subscription for that operational intent (even if that subscription was implicit for a different operational intent).  Yes, the intention there was to allow the DSS to create and manage an implicit subscription rather than providing an explicit subscription ID.

> In addition to having OI1's subscription mentioned in subscribers, I also assume that the subscription that gets attached is the one of OI1 (assuming that the initial implicit subscription for OI3 has been removed)

What do you mean by "gets attached"? (what gets attached to what?)  OI2 is in the Accepted state and does not need a subscription (and the step suggestion specifies "without subscription")

> Here, from my understanding, what should generally happen is that a new implicit subscription should be created and attached to OI1, as OI1 and OI2 are now entirely disjoint.

The DSS could create a new implicit subscription due to the update, but I would generally expect that the DSS creates and maintains a single implicit subscription per operational intent.  So, I would expect the implicit subscription for OI1 would be mutated to change time range.  OI2 has no subscription and therefore OI1 & OI2 being disjoint is irrelevant for OI1's subscription state.

> I am wondering if it would be acceptable for a DSS to not do anything with the implicit subscription, as it technically still covers both OI1 and OI2, although it also covers the interval from t_1 to t_2 where nothing exists? My hunch would be to not accept this, but I'd like a second opinion on that matter.

Not sure I follow; OI2 has no subscription, implicit or explicit.

> Here OI3 should be attached to the implicit subscription created in step 4 that now only covers OI2, assuming that step 6 caused the creation of a new implicit subscription.

I would generally expect implicit subscriptions not to be reused between operational intents by the DSS.  There are difficulties when a USS uses an implicit subscription for one operational intent as an explicit subscription for a second operational intent and we should write tests for those cases, but I believe those are more edge cases and can therefore be prioritized after the core set of tests confirming basic implicit subscription behavior described here.

**Comment by Shastick** [comment]
Here is a [possible cause](https://github.com/interuss/dss/issues/1056) for the residual subscriptions.

**Comment by Shastick** [comment]
This has been [addressed on the DSS](https://github.com/interuss/dss/pull/1109) and is now also [properly tested by the qualifier](https://github.com/interuss/monitoring/pull/720).

I expect the problem of residual subscriptions to be solve: if you witness this to be otherwise, please reopen.
