### ISSUE TITLE
[scd-spec] Update OpenAPI spec to allow null subscription on OIR

### ISSUE THREAD

**Issue by Shastick** [interuss/monitoring#806]
This issue's role is mostly to keep track of [this quirk](https://github.com/interuss/monitoring/blob/8f2dc5322229c42e72ad07078f5068f0b8cb0c2b/monitoring/uss_qualifier/scenarios/astm/utm/dss/oir_implicit_sub_handling.py#L440).

As a reminder:
 - The [SCD OpenAPI spec](https://github.com/astm-utm/Protocol/blob/63ba6c5ff9c9abb93c55fbdf2bffc0b089d10c4a/utm.yaml#L643) requires that the [OperationalIntentReference](https://github.com/astm-utm/Protocol/blob/63ba6c5ff9c9abb93c55fbdf2bffc0b089d10c4a/utm.yaml#L628) struct always define a `subscription_id` field.
 - However, the ASTM-F3548-v21 standard does not require a subscription to create OIRs in the ACCEPTED state
 - This led to the introduction of [this quirk](https://github.com/interuss/dss/pull/1005) on the DSS

A proper way to fix all this would be to update the OpenAPI specification to properly reflect the ASTM-F3548-v21 standard.

**Comment by Shastick** [comment]
cc @BenjaminPelletier and @mickmis 

This issue might better belong on some other project: please feel free to move it if required.

**Comment by mickmis** [comment]
@BenjaminPelletier if I interpret correctly your comment, it is then *not* desirable to update the OpenAPI to remove the requirement for this field to be present? Since here it is an error but it can be worked around. In that case we may close this issue.

**Comment by BenjaminPelletier** [comment]
Correct -- we can pretty freely add fields to our version of the API because the standard API [specifically enables this](https://github.com/astm-utm/Protocol/blob/master/utm.yaml#L14), but changing or removing things (changing data types, changing field names, changing whether a field is required, etc) requires a standard revision (e.g., ASTM F3548-24), or else the API we're using wouldn't be compatible with the standard API.

**Comment by Shastick** [comment]
Closing the issue, as this is likely not a change we'd like to do to the standard.
